### ISSUE TITLE
jenkins_job fails if job already exists

### ISSUE THREAD

**Issue by philicious** [chef-cookbooks/jenkins#285]
```
================================================================================
    Error executing action `create` on resource 'jenkins_job[git-vs-chef-sync]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '255'
    ---- Begin output of /usr/lib/jvm/java-7-oracle-amd64/bin/java -jar /var/chef/cache/jenkins-cli.jar -s http://localhost:8080 create-job git-vs-chef-sync < /var/chef/cache/gitvschef-config.xml ----
    STDOUT:
    STDERR: Job 'git-vs-chef-sync' already exists
    ---- End output of /usr/lib/jvm/java-7-oracle-amd64/bin/java -jar /var/chef/cache/jenkins-cli.jar -s http://localhost:8080 create-job git-vs-chef-sync < /var/chef/cache/gitvschef-config.xml ----
    Ran /usr/lib/jvm/java-7-oracle-amd64/bin/java -jar /var/chef/cache/jenkins-cli.jar -s http://localhost:8080 create-job git-vs-chef-sync < /var/chef/cache/gitvschef-config.xml returned 255

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:79:in `execute!'
    /var/chef/cache/cookbooks/jenkins/libraries/job.rb:125:in `block (2 levels) in <class:JenkinsJob>'
    /var/chef/cache/cookbooks/jenkins/libraries/job.rb:124:in `block in <class:JenkinsJob>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/hc-chef-jenkins/recipes/_jenkins.rb

     61: jenkins_job 'git-vs-chef-sync' do
     62:   config gitvschef
     63: end
     64:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/hc-chef-jenkins/recipes/_jenkins.rb:61:in `from_file'

    jenkins_job("git-vs-chef-sync") do
      action :create
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "hc-chef-jenkins"
      recipe_name "_jenkins"
      config "/var/chef/cache/gitvschef-config.xml"
    end
```

**Comment by schisamo** [comment]
@philicious I'm not sure what to tell you :frowning:. I assume the job in question was created before Chef was used to manage this master instance?

**Comment by philicious** [comment]
@schisamo This happened after a complete fresh bootstrap of the Jenkins node. All jobs are created by Chef. 
If you have no clue then leave it until someone else runs into this. I'm fine with having ignore_failure now in the jenkins_job resources

**Comment by priestjim** [comment]
I've run into this exact same issue. `-l debug` stops right after running `validate_config!`. Configuration files were manually created.

**Comment by dpetzel** [comment]
I've bumped into this today as well. In my case things were working fine and then I enabled github-auth. Following that being enabled I'm getting the exact same error. Turning authentication back off it goes back to working

Here is the snippet of debug logging:
```
[2015-01-30T07:08:26-08:00] INFO: Processing jenkins_job[myjob-test] action create (mycookbook::_jobs line 19)
[2015-01-30T07:08:26-08:00] DEBUG: Load jenkins_job[myjob-test] job information
[2015-01-30T07:08:28-08:00] DEBUG: Validate jenkins_job[myjob-test] configuration
[2015-01-30T07:08:29-08:00] INFO: Running queued delayed notifications before re-raising exception
[2015-01-30T07:08:29-08:00] DEBUG: Re-raising exception: Mixlib::ShellOut::ShellCommandFailed - jenkins_job[myjob-test] (mycookbook::_jobs line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
---- Begin output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 create-job myjob-test < /var/chef/cache/myjob-config.xml ----
STDOUT: 
STDERR: Job 'myjob-test' already exists
```

**Comment by schisamo** [comment]
So my hunch this is all related to authn issues. I believe the [current job lookup](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/job.rb#L198-L223) that [occurs in load_current_resource](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/job.rb#L86-L92) is basically returning nil so `Chef::Provider::JenkinsJob` proceeds thinking it's creating a brand new job vs updating an existing job.

**Comment by xbeta** [comment]
should it update if it is already existed? and not throwing exception?

**Comment by schisamo** [comment]
@xbeta That create vs update logic [already exists](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/job.rb#L117-L135). The issue is the look up of the existing job is failing in [load_current_resource](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/job.rb#L86-L92) because of authentication issues so the provider proceeds as if the job does not exist on the Jenkins master yet.

**Comment by philicious** [comment]
so just for getting this straight: is this a problem with my auth setup (using LDAP here) or is it a bug in jenkins cookbook that might get a fix ?

**Comment by schisamo** [comment]
@philicious I think it's your auth setup. Can you validate the executor is configured correctly by using another one of the resources that ships in this cookbook *before* the jenkins_jobs resource.

**Comment by philicious** [comment]
ok so I have jenkins_plugin resource before jenkins_job and the plugins run fine:
```
  * jenkins_plugin[token-macro] action install (up to date)
  * jenkins_plugin[git] action install (up to date)
  * jenkins_plugin[git-client] action install (up to date)
  * jenkins_plugin[github-api] action install (up to date)
  * jenkins_plugin[github] action install (up to date)
  * jenkins_plugin[ghprb] action install (up to date)
  * jenkins_plugin[ruby-runtime] action install (up to date)
  * jenkins_plugin[ansicolor] action install (up to date)
  * jenkins_plugin[jenkinswalldisplay] action install (up to date)
  * jenkins_plugin[embeddable-build-status] action install (up to date)
  * jenkins_plugin[instant-messaging] action install (up to date)
  * jenkins_plugin[ci-skip] action install (up to date)
  * jenkins_plugin[build-timeout] action install (up to date)
  * jenkins_plugin[categorized-view] action install (up to date)
  * jenkins_plugin[buildtriggerbadge] action install (up to date)
  * jenkins_plugin[slack] action install (up to date)
``

**Comment by stajkowski** [comment]
This is an auth issue.  I ran into this myself.  The problem: you need to set your security key up at the very top and the authentication setup at the very bottom.  This will most likely solve your issues.

The reason you get the error 'already exists' is due to probably the anonymous setup allowing view of the jenkins jobs only.  The problem is the resource.exists instance variable needs to access get-job which demands detailed information about the job to correctly set this value, and it is not allowed to anonymous for viewing.  This causes the return value of get-job to be nil.  The provider then believes that the job is not currently setup and tries to do a create-job.  This fails and you get the error.


# If security was enabled in a previous chef run then set the private key in the run_state
# now as required by the Jenkins cookbook
ruby_block 'set jenkins private key' do
  block do
    node.run_state[:jenkins_private_key] = admin_private_key
  end
  only_if { node.attribute?('security_enabled') || ::File.file?('/var/lib/jenkins/security_enabled') }
end


#...bunch of awesome chef things here


# Create the admin user before enabling security.
jenkins_user node['jenkinsapp']['admin']['username'] do
  password node['jenkinsapp']['admin']['password']
  public_keys [admin_public_key]
  not_if { node.attribute?('security_enabled') || ::File.file?('/var/lib/jenkins/security_enabled') }
  notifies :execute, 'jenkins_script[add_authentication]', :immediately
end

# Enable authentication and set the security model to allow admin rights
# to all logged-in users.
jenkins_script 'add_authentication' do
  command <<-EOH.gsub(/^ {4}/, '')
    import jenkins.model.*
    import hudson.security.*
    import org.jenkinsci.plugins.*
    def instance = Jenkins.getInstance()
    def hudsonRealm = new HudsonPrivateSecurityRealm(false)
    instance.setSecurityRealm(hudsonRealm)
    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    instance.setAuthorizationStrategy(strategy)
    instance.save()
  EOH
  notifies :create, 'ruby_block[set the security_enabled flag]', :immediately
  action :nothing
end

# Set the security enabled flag and set the run_state to use the configured private key
ruby_block 'set the security_enabled flag' do
  block do
    node.run_state[:jenkins_private_key] = admin_private_key
    node.normal['security_enabled'] = true
    Chef::Config[:solo] ? ::FileUtils.touch('/var/lib/jenkins/security_enabled') : node.save
  end
  action :nothing
end
