### ISSUE TITLE
Java path not set correctly on initial run when installing Jenkins via package

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/jenkins#366]
In attributes/default.rb, you set jenkins['java'] based on attributes that will not be set if relying on the Jenkins package installation to install Java.

Also, on the first run, the JAVA_HOME won't be set when the value is evaluated.  As such, the java value ends up being just "java".

However, the next run through JAVA_HOME is set so the value changes, updates /etc/sysconfig/jenkins, and forces a Jenkins restart.  This is dangerous and unexpected.  It needs to be evaluated at runtime or you need to put a dependency on the Java cookbook.

**Comment by nkadel-skyhook** [comment]
It's also a very dangerous idea to try and replace the much more powerful, effective, and consistent java coookbook with a few lines of local code that may override a a selected and configured java-1.8.0-openjdk with a new java-1.7.0-openjdk. If you're going to insist on insalling Java, use the Java cookbook in order to get consistent settings.

Jenkins on RHEL or CentOS also works just fine with Oracle JDK 7 and Oracle JDK 8 in my recent experience, so the java-1.7.0-openjdk is overspecific.

**Comment by iennae** [comment]
Hey folks,

100% agreed that we should take out java from installing via this cookbook, and instead recommend folks determine how they want to install java. We'll be updating this so that folks can do the right thing in their wrapper cookbooks.

**Comment by iennae** [comment]
Currently the cookbook doesn't install java (although it has the recipe), and it has a notice about deprecation. Do you folks feel this is sufficient in handling this problem?

**Comment by cheeseplus** [comment]
We advocate against using the in built java recipe fairly sternly and we'll probably remove this entirely in the future. Closing.
