### ISSUE TITLE
Can't create multiple credentials with the same username

### ISSUE THREAD

**Issue by FreakyDug** [chef-cookbooks/jenkins#447]
The code used to load existing credentials (https://github.com/chef-cookbooks/jenkins/blob/master/libraries/_helper.rb) uses the username as a unique key. Jenkins supports having multiple credentials with the same username, but if you try to do with through the cookbook, the two will be conflated and either overwrite or fail because they are different types.

**Comment by miguelaferreira** [comment]
I've had the same issue. In my case, I have a password credential and a private key credential for the same user. The code could do a bit more to differentiate those (since they are actually instances of different classes).

**Comment by alexlessard** [comment]
We can confirm this issue as well. Using v2.2.2 and noting that there has been no change in functionality around this behavior since then.

**Comment by willejs** [comment]
+1 on this. Its very confusing!

**Comment by chhsiung** [comment]
+1

This is preventing me from properly using the jenkins_password_credentials

**Comment by FreakyDug** [comment]
The same problem also means that if you change the username but keep the ID the same, chef will fail to update the credential but think it has succeeded. This is a problem if you, for example, want to swap out a username and password but keep the ID the same so jobs don't have to change.

**Comment by etki** [comment]
painful it is, +1

**Comment by iennae** [comment]
Hey folks,

Please check out version cookbook 4.0.0 thanks to work contributed by @borgstrom. Please verify whether this resolves the issue that you are having. Please note that this is a breaking change to how the previous versions of the cookbook worked. You will need to explicitly set the id for credentials rather than the username. The previous versions of this auto-generated the ids for you which was causing the behavior folks were reporting.
