### ISSUE TITLE
remove dependencies not needed by the custom resources

### ISSUE THREAD

**Issue by aespinosa** [chef-cookbooks/jenkins#460]
#138 doesn't explain the motivation as to why they are needed. But I would like to bring this topic back again.

The current dependencies are only needed by the recipe components of the cookbook. The custom resources seem to be self-contained. If the direction of this cookbook is to be a library cookbook, then removing such dependencies makes sense.

In my application cookbooks, I wanted the later version of the 'apt' cookbook. But I cannot use it because the dependency resolver (Berkshelf) forces me to use the (older) version in the Jenkins cookbook's metadata.rb. 

This will probably break some users' workflow that rely on the implicit dependencies. It will also reduce the included recipes to second class citizens.

**Comment by iennae** [comment]
As of 3.0 the apt and yum dependencies of this cookbook have been removed and replaced with compat_resource as we migrate to 12.0+ style resources. We've removed the base yum.conf configuration and apt-get update which was why the dependencies were there on yum and apt. 

We are definitely migrating to a style that allows folks to better lock down their cookbooks as they want to and updating documentation to reflect the need to include these requirements in their wrapper cookbooks.

We do still have the runit requirement due to hard coded aspects in the library portion of this cookbook, i.e. if you look at the HWRP slave_jnlp you'll see runit getting included. 

    def service_resource
      return @service_resource if @service_resource

      # Ensure runit is installed on the slave.
      recipe_eval do
        run_context.include_recipe 'runit'
      end

I hope the updates have helped resolve your apt issues, please reopen with more information if you'd like more clarity about the direction of this cookbook with regards to dependencies.
