### ISSUE TITLE
Jenkins 2.0 fails jenkins_user resource due to removal of email method

### ISSUE THREAD

**Issue by AbraxasJung** [chef-cookbooks/jenkins#470]
### Cookbook version

[Version of the cookbook where you are encountering the issue]
### Chef-client version

[Version of chef-client in your environment]
### Platform Details

[Operating system distribution and release version. Cloud provider if running in the cloud]
### Scenario:

[What you are trying to achieve and you can't?]
### Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
### Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]
### Actual Result:

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by AbraxasJung** [comment]
The mobile github reset inputs.

Jenkins 2.0 and jenkins_user resource fail because email method was removed. Remove email section from jenkins_user groovy and it works fine. Chef 12.4+

**Comment by gsreynolds** [comment]
FYI, it would appear that the error "unable to resolve class hudson.tasks.Mailer.UserProperty" when using jenkins_user resource with Jenkins 2.x is due to the [Mailer plugin](https://wiki.jenkins-ci.org/display/JENKINS/Mailer) not being included by default in a new 2.x install, seemingly unlike previous 1.x Jenkins versions. If you ensure that the Mailer plugin is installed before using the jenkins_user resource, the resource will not fail.

**Comment by StephenKing** [comment]
So this is solved by #496, isn't it?

**Comment by cheeseplus** [comment]
Yep, this should be solved with the above merge.
