### ISSUE TITLE
JNLP slave is configured to not use all the groups of the jenkins user

### ISSUE THREAD

**Issue by FreakyDug** [chef-cookbooks/jenkins#685]
### Cookbook version
5.0.6 (but it appears the same in master)

### Chef-client version
N/A

### Platform Details
Ubuntu 14.04 in a VMware VM

### Scenario:
I want jenkins jobs to be able interact with docker. In order to do this, I put the jenkins user in the docker group, so it would have permission to use the docker socket file. However, because the slave process is run with `chpst -u jenkins` (https://github.com/chef-cookbooks/jenkins/blob/master/templates/sv-jenkins-slave-run.erb#L10) the jenkins process only gets the jenkins group and ignores the docker group. This causes permission errors from docker.

What is the reason for running the process using chpst? Can we change it to use all the groups?

### Steps to Reproduce:
- Add the jenkins user to a new group
- Restart the slave
- Run a job that just runs `groups`

### Expected Result:
The result should be `jenkins docker` or whatever the other group you put it in was.

### Actual Result:
You just get `jenkins`.

**Comment by cdoughty-r7** [comment]
There is a fix for this on the master service template, just not on the slave for some mind boggling reason:
https://github.com/chef-cookbooks/jenkins/blob/master/templates/sv-jenkins-run.erb#L10
All that is needed is to have the slave use the same variable or a variable of the namespace `node` instead of `master`.
